---
name: Statistics-SDT
version: 0.032
author:
  - Roderick Garton
abstract: "Signal-detection theory (SDT) measures of sensitivity and bias"
license: perl
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  license: http://dev.perl.org/licenses/
